baseURL = 'https://lucidvagary.com/'
title = "Lucid Vagary"
theme = "mana"
languageCode = "en-us"
defaultContentLanguage = "en"

[pagination]
  pageSize = 10

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "catppuccin-macchiato"

[outputs]
  home = ["HTML", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  enableIntegrity = false
  relatedPostsCount = 3
  description = "Where Creativity Inspires Insight"
  author = "Sean"
  heroTitleLine1 = "LUCID VAGARY"
  heroTitleLine2 = "Where Creativity Inspires Insight"
  footerText = "Lucid Vagary"

  [params.buyMeACoffee]
    enabled = false

  [params.codeHighlight]
    darkTheme = "catppuccin-macchiato"
    lightTheme = "catppuccin-frappe"

  [params.copyright]
    startYear = 2026
    owner = "Sean"

  [params.admonitions]
    alertStyle = "favicon"

[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 20

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 30

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 40
